<?php

$urlRoutes = array(
    'index' => 'index',
    'wallpaper' => 'wallpapers/s',
    'wallpapers' => 'wallpapers/list',

    'add_wallpaper' => 'wallpapers/add',
    'admin_categories' => 'categories/admin',
    

    'login' => 'auth/login',
    'process_contact' => 'contact/process',
    'for_jobseekers' => 'pages/for_jobseekers',
    'job_alerts' => 'pages/job_alerts',
    'job_search' => 'pages/job_search',
    'work_with_us' => 'pages/work_with_us',
    'job_scams' => 'pages/job_scams',
    'career_advice' => 'pages/career_advice',
    'accounting_and_finance' => 'pages/accounting_and_finance',
    'drivers_and_operators' => 'pages/drivers_and_operators',
    'executive_recruitment' => 'pages/executive_recruitment',
    'health_recruitment' => 'pages/health_recruitment',
    'human_resources' => 'pages/human_resources',
    'it_and_digital' => 'pages/it_and_digital',
    'office_support' => 'pages/office_support',
    'production_workers' => 'pages/production_workers',
    'sales_and_marketing' => 'pages/sales_and_marketing',
    'technical_and_engineering' => 'pages/technical_and_engineering',
    'trades_and_labour' => 'pages/trades_and_labour',
    'temp_and_contract_recruitment' => 'pages/temp_and_contract_recruitment',
    'permanent_recruitment' => 'pages/permanent_recruitment',
    'executive_and_search' => 'pages/executive_and_search',
    'banking_and_financial_services' => 'pages/banking_and_financial_services',
    'construction_and_civil' => 'pages/construction_and_civil',
    'government' => 'pages/government',
    'manufacturing' => 'pages/manufacturing',
    'mining_and_resources' => 'pages/mining_and_resources',
    'renewable_energy' => 'pages/renewable_energy',
    'transport_and_logistics' => 'pages/transport_and_logistics',
    'recruitment_process_outsourcing' => 'pages/recruitment_process_outsourcing',
    'managed_service_provider' => 'pages/managed_service_provider',
    'volume_recruitment' => 'pages/volume_recruitment',
    'graduate_recruitment' => 'pages/graduate_recruitment',
    'total_talent' => 'pages/total_talent',
    'find_talent' => 'pages/find_talent',
    'psychometric_assessment' => 'pages/psychometric_assessment',
    'register' => 'register',
    'process_register' => 'register/process',
    'process_login' => 'register/login_processor',
    'administrator' => 'administrator',
    'administrator_login' => 'administrator/login',
    'administrator_register' => 'administrator/register',
    'admin_register_processor' => 'administrator/process_register',
    'process_admin_login' => 'administrator/login_processor',
    'administrator_jobs' => 'administrator/jobs',
    'admin_add_job' => 'administrator/add_job',
    'give' => 'contact/give',
    '404' => 'error_404',
    'mission'=>'mission',
    'vision'=>'vision',
    'events'=>'events',
    'registerSubscriber' => 'subscriber/addSubscriber',
    'sendMessage' => 'index/send_message',
    //
    //for the adimin section
    //
    'adminLogin' => 'adminlogin',
    'authentication' => 'adminlogin/authenticate', 
    'dashboard' => 'administrator/index',
    'logout' => 'administrator/logout',
    'uploadPhoto' => 'administrator/uploadPhoto',
    'photoUploader' => 'administrator/photoUploader',
    'adminViewPhotos' => 'administrator/viewPhotos',
    'deletePhoto' => 'administrator/deletePhoto',
    'deletePhotos' => 'administrator/deletePhotos',
    'addEvent' => 'administrator/addEvent',
    'adminEvents'=>'administrator/viewEvents',
    'deleteEvent'=>'administrator/deleteEvent',
    'deleteAllEvents' => 'administrator/deleteAllEvents',
    'visitors' => 'administrator/visitors',
    'addSermon' => 'administrator/addSermon',
    'viewSermons' => 'administrator/viewSermons',
    'adminVideos' => 'administrator/videos',
    'addVideo' => 'administrator/addVideo',
    'deleteVideo' => 'administrator/deleteVideo',
    'updateEvent' => 'administrator/updateEvent',
    'adminSubscribers' => 'administrator/subscribers',
    'deleteSubscriber' => 'administrator/deleteSubscriber',
    'contactMessages' => 'administrator/contactMessages',
    'replyMessage' => 'administrator/contactMessage',
    'sendEmail' => 'administrator/sendEmail',

);

define ("ROUTES", $urlRoutes);